# Generated by Django 3.1.4 on 2020-12-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201213_2114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
