# Generated by Django 3.1.4 on 2020-12-14 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductManager',
        ),
    ]
