# Generated by Django 3.1.4 on 2020-12-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_billingaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name_plural': 'Billing addresses'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping addresses'},
        ),
    ]
