# Generated by Django 3.1.4 on 2020-12-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20201214_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='address',
            new_name='address_b',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='city',
            new_name='city_b',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='state',
            new_name='state_b',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='zip_code',
            new_name='zip_code_b',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='address_s',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='city_s',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='state_s',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zip_code',
            new_name='zip_code_s',
        ),
    ]
